/* 색상 팔레트 */
import 'package:flutter/material.dart';


void changeColorTheme(String type) {
  mainAppBackgroundColor = const Color(0xFFFFFEFD);
  mainAppBarColor = const Color(0xFF5B3723);
  mainAppBarIconColor = const Color(0xFFFFFEFD);
  homeSliderActiveTrackColor = const Color(0xFF714F37);
  homeSliderInactiveTrackColor = const Color(0xFFE1D1B9);
  homeSliderthumbColor = const Color(0xFF9D866E);
  homeSliderOverlayColor = const Color(0xFF5B3723);
  homeSliderInactiveTickMarkColor = const Color(0xFFFFFEFD);
  homePriviewConatinerBackgroundColor = const Color(0xFFFFFEFD);
  homePriviewConatinerBoxShadowColor = const Color(0xFF5B3723);
  homeStartButtonColor = const Color(0xFF5B3723);
  loginMainTextColor = const Color(0xFF4B2615);
  loginSubTextColor = const Color(0xFF876950);
  loginHorizonBarColor = const Color(0xFF4B2615);
  loginBottomContainerColor = const Color(0xFF4B2615);
  loginLoginButtonColor = const Color(0xFF4B2615);
  drawerBackgroundColor = const Color(0xFFFFFEFD);
  drawerHeaderBackgroundColor = const Color(0xFF5B3723);
  drawerAvatarBackgroundColor = const Color(0xFFFFFEFD);
  drawerListIconColor = const Color(0xFF1F1E1D);
  shopAppBarColor = const Color(0xFF5B3723);
  shopItemConatinerBackgroundColor = const Color(0xFFFFFEFD);
  shopContentTypeActiveColor = const Color(0xFF876950);
  shopContentTypeDisableColor = const Color(0xFFE1D1B9);
  signupTextInputBorderColor = const Color(0xFF4B2615);
  signupDropdownButtonBorderColor = const Color(0xFF4B2615);
  signupNextButtonTouchableColor = const Color(0xFF4B2615);
  signupNextButtonUntouchableColor = const Color(0xFFCFCAC7);
  signupExplanTextColor = const Color(0xFF4B2615);
  signupStepIconActiveColor = const Color(0xFF4B2615);
  signupStepIconDisableColor = const Color(0xFFCFCAC7);
  recordCalendarPickerColor = const Color(0xFFE1D1B9);
  recordItemConatinerBackgroundColor = const Color(0xFFFFFEFD);
  recordContentTypeActiveColor = const Color(0xFF876950);
  recordContentTypeDisableColor = const Color(0xFFE1D1B9);
  successLoginButtonColor = const Color(0xFF4B2615);
  successMainTextColor = const Color(0xFF4B2615);
  loadingBackgroundColor = const Color(0xFF5B3723);
  enterMainTextColor = const Color(0xFF5B3723);
  enterSubTextColor = const Color(0xFF5B3723);
  enterLoginButtonColor = const Color(0xFF5B3723);
  enterSignupButtonColor = const Color(0xFFE1D1B9);
  agreeCheckButtonActiveColor = const Color(0xFF4B2615);
  themeWhite = const Color(0xFFFFFEFD);
  themeBlack = const Color(0xFF1F1E1D);
  themeGrey = const Color(0xFFCFCAC7);
  themePrimaryColor = const Color(0xFF4B2615);
}

late final Color mainAppBackgroundColor;
late final Color mainAppBarColor;
late final Color mainAppBarIconColor;
late final Color homeSliderActiveTrackColor;
late final Color homeSliderInactiveTrackColor;
late final Color homeSliderthumbColor;
late final Color homeSliderOverlayColor;
late final Color homeSliderInactiveTickMarkColor;
late final Color homePriviewConatinerBackgroundColor;
late final Color homePriviewConatinerBoxShadowColor;
late final Color homeStartButtonColor;
late final Color loginMainTextColor;
late final Color loginSubTextColor;
late final Color loginHorizonBarColor;
late final Color loginBottomContainerColor;
late final Color loginLoginButtonColor;
late final Color drawerBackgroundColor;
late final Color drawerHeaderBackgroundColor;
late final Color drawerAvatarBackgroundColor;
late final Color drawerListIconColor;
late final Color shopAppBarColor;
late final Color shopItemConatinerBackgroundColor;
late final Color shopContentTypeActiveColor;
late final Color shopContentTypeDisableColor;
late final Color signupTextInputBorderColor;
late final Color signupDropdownButtonBorderColor;
late final Color signupNextButtonTouchableColor;
late final Color signupNextButtonUntouchableColor;
late final Color signupExplanTextColor;
late final Color signupStepIconActiveColor;
late final Color signupStepIconDisableColor;
late final Color recordCalendarPickerColor;
late final Color recordItemConatinerBackgroundColor;
late final Color recordContentTypeActiveColor;
late final Color recordContentTypeDisableColor;
late final Color successLoginButtonColor;
late final Color successLoginButtonTextColor;
late final Color successMainTextColor;
late final Color loadingBackgroundColor;
late final Color enterMainTextColor;
late final Color enterSubTextColor;
late final Color enterLoginButtonColor;
late final Color enterSignupButtonColor;
late final Color agreeCheckButtonActiveColor;
late final Color themeWhite;
late final Color themeBlack;
late final Color themeGrey;
late final Color themePrimaryColor;

const Color colorSuccess100 = Color(0xFFF1FCD3);
const Color colorSuccess200 = Color(0xFFE0F9A8);
const Color colorSuccess300 = Color(0xFFC5EE7A);
const Color colorSuccess400 = Color(0xFFA8DE57);
const Color colorSuccess500 = Color(0xFF80C926);
const Color colorSuccess600 = Color(0xFF65AC1B);
const Color colorSuccess700 = Color(0xFF4D9013);
const Color colorSuccess800 = Color(0xFF37740C);
const Color colorSuccess900 = Color(0xFF286007);
const Color colorInfo100 = Color(0xFFD1FDF0);
const Color colorInfo200 = Color(0xFFA4FBE9);
const Color colorInfo300 = Color(0xFF75F3E4);
const Color colorInfo400 = Color(0xFF52E7E2);
const Color colorInfo500 = Color(0xFF1ECFD8);
const Color colorInfo600 = Color(0xFF15A4B9);
const Color colorInfo700 = Color(0xFF0F7D9B);
const Color colorInfo800 = Color(0xFF095A7D);
const Color colorInfo900 = Color(0xFF054267);
const Color colorWarning100 = Color(0xFFFEF8D0);
const Color colorWarning200 = Color(0xFFFEF0A1);
const Color colorWarning300 = Color(0xFFFDE572);
const Color colorWarning400 = Color(0xFFFBDA4F);
const Color colorWarning500 = Color(0xFFF9C816);
const Color colorWarning600 = Color(0xFFD6A610);
const Color colorWarning700 = Color(0xFFB3870B);
const Color colorWarning800 = Color(0xFF906907);
const Color colorWarning900 = Color(0xFF775404);
const Color colorDanger100 = Color(0xFFFFECE0);
const Color colorDanger200 = Color(0xFFFFD5C2);
const Color colorDanger300 = Color(0xFFFFB9A4);
const Color colorDanger400 = Color(0xFFFF9E8D);
const Color colorDanger500 = Color(0xFFFF7268);
const Color colorDanger600 = Color(0xFFDB4C4E);
const Color colorDanger700 = Color(0xFFB73441);
const Color colorDanger800 = Color(0xFF932136);
const Color colorDanger900 = Color(0xFF7A1131);